### ISSUE TITLE
processo suicidato

### ISSUE THREAD

**Issue by blackout314** [dlion/smagenBot#4]
```
Error: Error on getUpdates
    at /home/user/smagenBot/index.js:28:13
    at Request._callback (/home/user/smagenBot/bin/smagenBot.js:27:9)
    at self.callback (/home/user/smagenBot/node_modules/request/request.js:197:22)
    at Request.emit (events.js:95:17)
    at Request.onRequestError (/home/user/smagenBot/node_modules/request/request.js:854:8)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1548:9)
    at CleartextStream.emit (events.js:95:17)
    at Socket.onerror (tls.js:1456:17)
    at Socket.emit (events.js:117:20)
```

**Comment by dlion** [comment]
@blackout314 è stata lanciata l'eccezione in index.js alla linea 28, hai avuto problemi nel metodo getUpdates

**Comment by blackout314** [comment]
si lo sapevo era per renderti partecipe del problema.. provo a fixarlo

**Comment by dlion** [comment]
@blackout314 Ma a me funge perfettamente O.o

**Comment by blackout314** [comment]
che versione di node stai usando? io 0.10.x

**Comment by dlion** [comment]
@blackout314 la 0.12.5 ma non credo che c'entri node.
L'eccezione viene lanciata quando:

``` js
if(err)
```

``` js
if (body === null)
```

Quindi per qualche motivo tu non riesci a prendere un body corretto dal server di telegram

**Comment by blackout314** [comment]
eh ma perche accade? misa che introdurro un sistema di logging cosi ci si rende conto melgio

**Comment by dlion** [comment]
@blackout314 Aggiungi un console.log(body) poco prima dell'if all'interno di index.js
A me non succede quindi è un problema del tuo bot che probabilmente ha difficoltà a ricevere i dati dal server.
il token è scritto in maniera corretta all'interno del file di conf ?

**Comment by blackout314** [comment]
il token è scritto giusto, diciamo che il bot è in "produzione" su una vps di cloudatcost (servizio scadente ma ottimo per prove)

**Comment by dlion** [comment]
@blackout314 Sì, anche io lo faccio girare su una vps di C@C, metti il console.log e vedi cosa restituisce il body perché è un problema remoto e non del bot in sé.

**Comment by blackout314** [comment]
chiaro, ci avevo pensato che fosse un problema non dello scriptino in se, ma in ogni caso "muore" quindi sto cercando di pensare un workaround o un modo per renderlo piu resiliente a questi errori

intanto dall'else ho tolto l'eccezione

**Comment by dlion** [comment]
@blackout314 Ma è giusto che muore se non riesce a contattare il server remoto.
Un bot che non può prendere i messaggi dal server è un bot inutile.

**Comment by blackout314** [comment]
si ma puo capitare che non riesca a prendere i messaggi per un picco di ping elevanto in quel momento, perche altrimenti non si spiega questo "malfunzionamento" a macchia di leopardo.. no? a te funziona, a me ogni tanto (da ieri sera ben 3 volte) muore

**Comment by dlion** [comment]
@blackout314 È capitato anche a me, è colpa di quelli di telegram:

``` html
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.9.1</center>
</body>
</html>
```

Questo è cosa mi ha restituito body.

Per fixare basta catchare l'eccezione.

**Comment by blackout314** [comment]
a me invece sta dando problemi telegram proprio
dopo debug approfondito ho scoperto che

chiamando

https://api.telegram.org/botAPIKEY/getUpdates

mi torna gli status NON AGGIORNATI l'ultimo resta sempre

```
"message":{"message_id":335,"from":{"id":49544016,"first_name":"Carlo","last_name":"Denaro","username":"blackout314"},"chat":{"id":-11250216,"title":"GrayHats_Rooms"},"date":1435494787,"left_chat_participant":{"id":85828888,"first_name":"Bitcointalk","username":"bitcointalk_bot"}}}]}
```

che è vecchio e quindi non torna praticamente niente dei nuovi

**Comment by dlion** [comment]
Quindi è un problema di telegram ?
Prova a giocare con il parametro `offset` su `getUpdates` e vedi cosa ritorna

**Comment by blackout314** [comment]
a ora siamo passati a 339 con questo timing

```
"message":{"message_id":339,"from":{"id":49544016,"first_name":"Carlo","last_name":"Denaro","username":"blackout314"},"chat":{"id":-2572583,"title":"GrayHats_Lab"},"date":1435494940,"text":"\/extra@bitcointalk_bot"}}]}
```

secondo me non hanno considerato il carico (troppo successo) xke se guardi la date siamo ancora indietro, con l'offset c'ho giocato ma le chiamate (sopra) le faccio a mano (GET)

**Comment by TheZ3ro** [comment]
Comunque ragazzi, sono problemi dei server di telegram, anche io spesso ricevo dei 502
o il bot rimane indietro e interpreta più volte gli stessi messaggi.

Speriamo che risolvano.

**Comment by dlion** [comment]
Io ho appena verificato che la mia soluzione worka senza problemi e senza reinterpretare i messaggi vecchi, pur essendo un problema del server di telegram.
Chiudo.

**Comment by blackout314** [comment]
confermo.. creato altro bot... STESSO codice... funziona mah

**Comment by blackout314** [comment]
ps: mo faccio "screen" dalla webcam e me li invio :smile:
