### ISSUE TITLE
Separate plugins

### ISSUE THREAD

**Issue by G07cha** [dlion/smagenBot#9]
Give users ability to install plugins right from chat, for example using command: `/install <path to repository>`

For now I see 2 cons:
- Separate core and components
- Allow authors to easily create own plugins and push it to production

**Comment by dlion** [comment]
Currently the core is separated from the plugins see `makeAction` method.
To add a plugin you have to do:
- Write a plugin (see the examples in the plugins directory or in the readme)
- put it on the plugins directory
- add it on the `list.json` file

That's all!

Everything without restart the bot.

About `/install` command I should download `<url>` file, put it into plugins directory and write it into `list.json` file.

**Comment by G07cha** [comment]
As I understand, for now here only two ways to install plugins:
- Create PR with plugin to this repository and wait until it will be merged(or not)
- Manually add plugin to folder and to list

First point will cause PRs hell, like in [hombrew](https://github.com/Homebrew/homebrew/pulls). So basicly idea is to let users write, install and share their plugins without any restictions and limitations(only by API)

**Comment by dlion** [comment]
Well, if you want to share your plugins you can share your plugins dir o just your plugin, if I want your plugin I just download your file and add it into plugins dir and into list file.
Anyway on the plugins dir there are examples made just for fun, if you want to use your bot obviously you should write your own plugins based on your needs.

Consider smagenBot like a `framework` to use your plugins. (I run my bot on my own server for my own needs)

**Comment by G07cha** [comment]
Okay, I'm still want to have simple plugin installation for smagenBot, but if you don't want this feature at all - close this issue.

**Comment by dlion** [comment]
I agree with you, I'll write a good solution for this problem, thank you!
Obviously any PR are welcome!

**Comment by G07cha** [comment]
Thanks, but I would like to keep this issue open until it's implemented so others will see and know where their efforts needed.
